# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6645cfbf60e513cda2bc57fc4d946b67a035d405f54f825eda02c84292844ef454980e56b3057c8ee4f9ae8face3747e03a552eae7d3a1ae8f685d43654e137c

test:
  secret_key_base: c2e188e4576c5928f6feab624689e310cf53d8fb830ca8c3ae4120a909aa91fd9878790ff77539e3fc0fe4925e56b9a841c46c8775a424f9968e4f21a9bc2d3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
